baseURL: http://eric.young.li/
languageCode: en-us
title: Eric Li

params:
  # ga: 'G-65504XST5T'
  goatCounter: 'ericli'
  tagline: I craft thoughtfully considered and executed digital experiences for users through design and code.

permalinks:
  work: /:sections[last]-:filename/

disableKinds:
  - "taxonomy"
  - "term"
  - "RSS"
markup:
  goldmark:
    renderer:
      unsafe: true