baseURL: http://eric.young.li/
languageCode: en-us
title: Eric Li

params:
  # ga: 'G-65504XST5T'
  goatCounter: 'ericli'
  tagline: Eric Li is a product leader, designer, software engineer, and educator based in <nobr>New York</nobr>.

permalinks:
  work: /:sections[last]-:filename/

disableKinds:
  - "taxonomy"
  - "term"
  - "RSS"
markup:
  goldmark:
    renderer:
      unsafe: true